# Generated by Django 3.2.5 on 2021-08-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSampl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('period1', models.CharField(max_length=50)),
                ('period2', models.CharField(max_length=50)),
                ('period3', models.CharField(max_length=50)),
                ('period4', models.CharField(max_length=50)),
                ('period5', models.CharField(max_length=50)),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.subjects')),
            ],
        ),
    ]
