# Generated by Django 3.2.5 on 2021-08-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_adminhod_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.courses'),
        ),
    ]
