# Generated by Django 3.2.5 on 2021-07-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20210724_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='session_start_end',
            new_name='session_end_year',
        ),
    ]
