# Generated by Django 3.2.5 on 2021-08-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_staffs_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='semesters',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
