# Generated by Django 3.2.5 on 2021-08-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20210805_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
