# Generated by Django 3.2.5 on 2021-08-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_question_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester'),
        ),
    ]
