# Generated by Django 3.2.5 on 2021-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_question_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='leave_end_date',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
