# Generated by Django 3.2.5 on 2021-08-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_alter_assignment_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='student_id',
        ),
    ]
