# Generated by Django 3.2.5 on 2021-08-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_assignmentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentanswer',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student_management_app.question'),
        ),
    ]
