# Generated by Django 3.2.5 on 2021-08-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_auto_20210809_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentanswer',
            name='question_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student_management_app.assignment'),
        ),
    ]
