# Generated by Django 3.2.5 on 2021-08-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_alter_assignmentanswer_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='semester_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='semester_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester'),
        ),
    ]
