# Generated by Django 3.2.5 on 2021-08-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_alter_attendancereport_attendance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.attendance'),
        ),
    ]
