# Generated by Django 3.2.5 on 2021-08-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0023_auto_20210810_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester'),
        ),
    ]
